#!/bin/bash

# misc
alias tf='tail -f'
alias ln='ln -v'
alias mkdir='mkdir -p'
alias ...='../..'
alias ....='../../..'
alias df='df -h'

# grep
export GREP_COLOR='3;33'
alias grep='grep --color=auto'

# fzf
alias fc='grep --line-buffered --color=never -r "" * | fzf'

# Enable aliases to be sudo'ed
alias sudo='sudo '

# ls / exa
if installed exa; then
  alias ls='exa -F'
  alias l='exa -F'
  alias lh='exa -AlhF'
  alias ll='exa -lgF --git'
  alias la='exa -algF --git'
  alias lsd='exa -dF */'
  alias lt='exa -lgFs modified'
else
  # add formatting and color to `ls`
  # Detect which `ls` flavor is in use
  export CLICOLOR=1
  export LSCOLORS=ExFxCxDxBxegedabagacad
  export LS_COLORS="di=36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34:su=0:sg=0:tw=0:ow=0:"
  if ls --color > /dev/null 2>&1; then # GNU `ls`
    colorflag="--color"
  else # BSD `ls`
    colorflag="-G"
  fi
  alias ls="command ls -Fh $colorflag"
  alias l='ls'
  alias lh='ls -Alh'
  alias ll='ls -Fhl'
  alias la='ls -algF --git'
  alias lsd="ls -d */"
  alias lt='ls -hltr'
fi

# editor
# Emacs
if installed emacs; then
  emacs="$(which emacs)"
  emacsclient="$(which emacsclient)"

  alias ed="$emacs --daemon"
  alias e="$emacsclient --no-wait"
  alias en="$emacsclient -c --no-wait"

  installed eless && alias man='PAGER=less man -P eless'
fi

# neovim / vim
if installed nvim; then
  alias vi='nvim'
  alias vim='nvim'
  export EDITOR="$(which nvim)"
  export MANPAGER="nvim -c 'set ft=man' -"
elif installed vim; then
  alias vi='vim'
  export EDITOR="$(which vim)"
fi

# PAGER
if installed vimpager; then
  export PAGER="$(which vimpager)"
  alias less="$PAGER"
  alias zless="$PAGER"
elif installed pygmentize; then
  export LESS=' -R '
  export LESSOPEN='|pygmentize -f terminal256 -g %s'
  alias more='less'
elif installed source-highlight; then
  export LESS=' -R '
  export LESSOPEN='| /usr/local/bin/src-hilite-lesspipe.sh %s'
  alias less='less -m -g -i -J --underline-special --SILENT'
  alias more='less'
fi

# git
# tell git to non-interactively merge commits
export GIT_MERGE_AUTOEDIT=no
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gcm="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias grpl="git reset HEAD --hard; git pull"
alias glog='git log --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'

# tmux
alias t='tmux'
alias tt='tmux attach; or tmux new'

# ssh
alias sst='ssh -t "tmux -CC attach; or tmux -CC"'

# Network
alias whats-my-ip='curl -s https://diagnostic.opendns.com/myip'
alias dis='drill +nocmd +noall +answer'

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# GRC
if installed grc; then
  alias colourify="$(which grc) -es --colour=auto"
  alias configure='colourify ./configure'
  alias diff='colourify diff'
  alias make='colourify make'
  alias gcc='colourify gcc'
  alias g++='colourify g++'
  alias as='colourify as'
  alias gas='colourify gas'
  alias ld='colourify ld'
  alias netstat='colourify netstat'
  alias ping='colourify ping'
  alias traceroute='colourify traceroute'
  alias tracepath='colourify -c conf.traceroute tracepath'
  alias arp='colourify -c conf.traceroute arp'
  alias tail='colourify -c conf.log tail'
  alias ps='colourify -c conf.ps ps'
  alias ifconfig='colourify -c conf.traceroute ifconfig'
  alias nmap='colourify -c conf.nmap nmap'
  alias lsof='colourify -c conf.traceroute lsof'
  alias dig='colourify -c conf.traceroute dig'
  alias host='colourify -c conf.traceroute host'
  alias drill='colourify -c conf.traceroute drill'
  alias curl='colourify -c conf.curl curl'
fi

case $(uname) in
  Linux) ;;
  'CYGWIN*') ;;
  Darwin)
    # Show/hide hidden files in Finder
    alias show-hidden-files="defaults write com.apple.finder AppleShowAllFiles -bool true; and killall Finder"
    alias hide-hidden-files="defaults write com.apple.finder AppleShowAllFiles -bool false; and killall Finder"

    # Merge PDF files
    # Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
    alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'
    ;;
esac
