#!/bin/zsh

# misc
alias tlf="tail -f"
alias ln='ln -v'
alias mkdir='mkdir -p'
alias ...='../..'
alias df='df -h'

# grep
alias -g G='| grep'
alias -g M='| less'
alias -g L='| wc -l'
alias -g ONE="| awk '{ print \$1}'"
alias grep='grep --color=auto'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# ls
# add formatting and color to `ls`
# Detect which `ls` flavor is in use
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi
alias ls="command ls -Fh ${colorflag}"
alias l='ls'
alias lh='ls -Alh'
alias ll='ls -Fhl'
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# vim
alias vi='vim'

# git
alias g="git"

# Network
alias whats-my-ip="dig +short myip.opendns.com @208.67.222.222 @208.67.220.220"
alias dis='dig +nocmd +noall +answer'
alias listening-ports='netstat -ntlp | grep LISTEN'
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# transmission-remote-cli
if hash transmission-remote-cli 2>/dev/null; then
  alias trcli='transmission-remote-cli'
fi

# GRC ######################################################
GRC=`which grc`
if [ "$TERM" != dumb ] && [ -n "$GRC" ]
then
  alias colourify="$GRC -es --colour=auto"
   alias configure='colourify ./configure'
   alias diff='colourify diff'
   alias make='colourify make'
   alias gcc='colourify gcc'
   alias g++='colourify g++'
   alias as='colourify as'
   alias gas='colourify gas'
   alias ld='colourify ld'
   alias netstat='colourify netstat'
   alias ping='colourify ping'
   alias traceroute='colourify /usr/sbin/traceroute'
   alias arp='colourify -c conf.traceroute arp'
  alias tail='colourify -c conf.log tail'
  alias ps='colourify -c conf.ps ps'
  alias ifconfig='colourify -c conf.traceroute ifconfig'
  alias nmap='colourify -c conf.nmap nmap'
  alias lsof='colourify -c conf.traceroute lsof'
  alias dig='colourify -c conf.traceroute dig'
  alias host='colourify -c conf.traceroute host'
  alias curl='colourify -c conf.curl curl'
fi

# Sublime Text #############################################

if [[ $('uname') == 'Linux' ]]; then
  if [ -f '/usr/bin/sublime_text' ]; then
    st_run() { nohup /usr/bin/sublime_text $@ > /dev/null & }
  else
    st_run() { nohup /usr/bin/sublime-text $@ > /dev/null & }
  fi
  alias st=st_run
elif  [[ $('uname') == 'Darwin' ]]; then
  local _sublime_darwin_subl=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl
  # Check if Sublime is installed in user's home application directory
  if [[ -a $HOME/${_sublime_darwin_subl} ]]; then
    alias st='$HOME/${_sublime_darwin_subl}'
  else
    alias st='${_sublime_darwin_subl}'
  fi
elif  [[ $('uname') == 'CYGWIN' ]]; then
  alias st=`which subl`
fi

# CYGWIN ###################################################

if [[ "$OSTYPE" == "CYGWIN"* ]]; then
  # Flush Directory Service cache
  alias flush="ipconfig /flushdns"
fi


# Mac OS X #################################################
if [[ "$OSTYPE" == "darwin"* ]]; then

   # open man page in Preview
   pman()
   {
   	man -t "${1}" | open -f -a /Appllication/Preview.app/
   }

   # Change Directory to the active Finder window (else ~/Desktop)
  function cdf()
  {
    local fPath=`osascript -e '
    tell app "finder"
       try
          set folderPath to (folder of the front window as alias)
       on error
          set folderPath to (path to desktop folder as alias)
       end try
       POSIX path of folderPath
    end tell'
    `;
    echo "cd $fPath";
    cd "$fPath" > /dev/null
  }

   # Dash
   dash() { open "dash://$*" }

   # Get OS X Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
  alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm install npm -g; npm update -g; sudo gem update --system; sudo gem update'

  # Flush Directory Service cache
  alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

  # Recursively delete `.DS_Store` files
  alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

  # Empty the Trash on all mounted volumes and the main HDD
  # Also, clear Apple’s System Logs to improve shell startup speed
  alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

  # Show/hide hidden files in Finder
  alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
  alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

  # Merge PDF files
  # Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
  alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

  # Disable Spotlight
  alias spotoff="sudo mdutil -a -i off"
  # Enable Spotlight
  alias spoton="sudo mdutil -a -i on"

fi
