* TODO Eshell =rm= hangs when pressing =RET=
Actually, it is working, it just takes a long time and gives zero feedback. This is especially problematic when working over slow links and performing bulk operations. Can we fix this?
** Takes too long
** Gives zero feedback (doesn't even go to new line when pressing =RET= until it is completely done)
** Outputs =t= for each file deleted. It should give the same feedback as =*rm=.
* TODO Desktop should restore eshell buffers
=desktop-plus.el= could be used for this. It currently has support for shell, but not eshell.
* TODO Figure out magit wip modes
* TODO Mojave issues [3/4]
** TODO Parinfer is slow
* TODO Get Eshell/tramp to cache and/or save passwords [2/4]
Enable logging with =(setq auth-source-debug t)=
** TODO What about when sudo is called in other ways, such as from a script? It doesn't seem to cache the password then.
** TODO How to ignore password prompting for just for a specific command?
See:
#+BEGIN_SRC emacs-lisp
(add-hook 'comint-output-filter-functions
          'comint-watch-for-password-prompt)
#+END_SRC
This is already added. do we have to do something else?
* TODO Implement =grc= in elisp
=highlight-things.el=
