taps:
  - homebrew/core
  - homebrew/fuse
  - caskroom/cask
  - homebrew/php
  - neovim/neovim

recipes:
  - ack
  - bash
  - bash-completion
  - chicken
  - homebrew/php/composer
  - ctags
  - exa
  - fasd
  - fish
  - fswatch
  - fzf
  - gawk
  - git
  - git-extras
  - gnupg
  - gpg-agent
  - graphviz
  - grc
  - grep
  - h2
  - highlight
  - httrack
  - hugo
  - iftop
  - ipcalc
  - iperf3
  - ldns
  - less
  - librsvg
  - libusb-compat
  - lnav
  - lumo
  - lynx
  - make
  - maven
  - minicom
  - mosh
  - ncdu
  - neovim
  - nmap
  - p7zip
  - perl
  - homebrew/php/php72
  - planck
  - postgresql
  - pv
  - pwgen
  - python
  - python3
  - ranger
  - rbenv
  - reattach-to-user-namespace
  - ripgrep
  - rlwrap
  - ruby
  - sbcl
  - shared-mime-info
  - shellcheck
  - sipcalc
  - source-highlight
  - speedtest-cli
  - ssh-copy-id
  - sshfs
  - texinfo
  - the_silver_searcher
  - thefuck
  - tig
  - tmux
  - tree
  - ttygif
  - unison
  - utf8proc
  - vimpager
  - watch
  - wget
  - zplug
  - lua

casks:
  - 1password
  - betterzipql
  - emacs
  - iina
  - iterm2
  - flux
  - java
  - jump-desktop
  - keepassx
  - keka
  - osxfuse
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - quicklook-csv
  - quicklook-json
  - slack
  - sublime-text
  - suspicious-package
  - vmware-fusion
  - webcatalog
  - webpquicklook
  - webtorrent
  - hammerspoon
