#!/usr/bin/env sh

TMPDIR="${TMPDIR:-$(mktemp)}"
before="${TMPDIR}emacs-source-sh-before"
after="${TMPDIR}emacs-source-sh-after"
elisp="${TMPDIR}emacs-source-sh.el"

env >"$before"
eval "$@" && env >"$after"
awk 'FNR==NR{a[$0]++;next}(!($0 in a))' "$before" "$after" | \
  sed 's/\([^=]*\)=\(.*\)/(setenv "\1" "\2"\)/g' >"$elisp"
