#!/bin/sh
# Print 256 background and foreground colors in a grid

for i in {0..255}; do
	printf "\033[48;5;${i}m %03d\033[0m" $i
	printf "\033[38;5;${i}m %03d\033[0m   " $i
	[ $((($i + 1) % 8)) -eq 0 ] && printf "\n"
done

printf '\033[0m'
