#!/usr/bin/env bash
# Return the first match for regular expression ($2) in string ($1)
# Based on (https://stackoverflow.com/a/22539067)

typeset ec
unset -v re_match # initialize output variable
[[ $1 =~ $2 ]] # perform the regex test
ec=$? # save exit code
if [[ $ec -eq 0 ]]; then # copy result to output variable
  [[ -n $BASH_VERSION ]] && re_match=( "${BASH_REMATCH[@]}" )
  [[ -n $ZSH_VERSION ]]  && re_match=( "${match[@]}" )
fi
exit $ec
