#!/bin/bash
# Save config for Atom Editor

save_dir="$1"
save_file="$1/atom.txt"

if installed apm; then
  echo "Saving Atom config files to $save_file..."
  apm list --bare --installed --dev false > "$save_file"
else
  echo "Atom not found, skipping"
fi
