#!/bin/bash
# Save ruby gems

save_dir="$1"
save_file="$save_dir/ruby_gems.txt"

if installed gem; then
  echo "Saving packages list to: $save_file"
  ruby -e 'puts Gem::Specification.map {|a| a.name}' > "$save_file"
else
  echo "gem not found, skipping"
fi

# cat "$save_file" | xargs gem install
