#!/bin/bash
# Save python packages

save_dir="$1"
save_file="$save_dir/pip-packages.txt"

installed pip && pip=pip
installed pip3 && pip=pip3

if [ "$pip" ]; then
  echo "Saving packages list to: $save_file"
  "$pip" list --user --format=columns | awk 'NR>2 {print $1}' > "$save_file"
else
  echo "pip not found, skipping"
fi
