#!/bin/bash
# Save npm packages

save_dir="$1"
save_file="$save_dir/packages.json"

if installed npm; then
  echo "Saving global npm packages to: $save_file..."
  npm -g ls --depth=0 --json > "$save_file"
else
  echo "npm not found, skipping"
fi
