#!/usr/bin/env sh

TMPDIR="${TMPDIR:-$(mktemp)}"
before="${TMPDIR}emacs-source-sh-before"
after="${TMPDIR}emacs-source-sh-after"
elisp="${TMPDIR}emacs-source-sh.el"

env >"$before-env"
alias >"$before-alias"
eval "$@" && env >"$after-env" && alias >"$after-alias"
if [ $? -eq 0 ]; then
  comm -13 <(sort "$before-env") <(sort "$after-env") | \
    sed 's/\([^=]+\)=\(.*\)/(setenv "\1" "\2"\)/g' >"$elisp"
  comm -13 <(sort "$before-alias") <(sort "$after-alias") | \
    sed 's/alias \([^=]+\)/"\1"/g' >>"$elisp"
else
  echo An error occurred executing command: "$@"
fi
# rm "${TMPDIR}emacs-source-sh"*
