#!/bin/bash

[ "$BASH_VERSION" ] && shopt -s nullglob
[ "$ZSH_VERSION" ] && setopt null_glob

declare -a SSH_KEYS=( ${HOME}/.ssh/*_?sa )

SSH_ENV="$HOME/.ssh/environment"
SSH_ADD="/usr/bin/ssh-add"
SSH_AGENT="/usr/bin/ssh-agent"

start_agent () {
  echo "Starting SSH agent..."
  ${SSH_AGENT} | sed 's/^echo/#echo/' > "${SSH_ENV}"
  . "${SSH_ENV}"
  echo "Adding keys:"
  echo "${SSH_KEYS[@]}"
  ${SSH_ADD} "${SSH_KEYS[@]}"
}

[ -f "${SSH_ENV}" ] && . "${SSH_ENV}"
ps -ef | grep ${SSH_AGENT_PID} | grep -q ssh-agent || start_agent
