#!/usr/bin/env bash
# Print a justified row for a simple table
# table_row COLUMN_1 [COLUMN_2 ...]

col_length=$((($(tput cols) - 2) / $# - 3))
printf "| "
for col in "$@"; do
  (( ${#col} > $col_length )) && col="${col:0:(($col_length-3))}..."
  printf "%${col_length}s | " "$col"
done
echo
