#!/bin/bash
# Update Atom Editor

if installed apm; then
  echo "Updating Atom..."
  # apm does weird things if we happen to be in an npm project directory
  pushd /tmp >/dev/null
  apm upgrade --no-confirm
  apm clean
  popd
else
  echo "Atom not found, skipping"
fi
