#!/usr/bin/env sh

if installed cpan; then
  installed cpanm &&
    cpanm --self-upgrade ||
    curl -L https://cpanmin.us | perl - App::cpanminus
  cpanm --notest App::cpanoutdated
  cpan-outdated -p | cpanm -q
fi
