#!/bin/bash
# Update python packages

. shell_utils

if installed pip; then
	echo "Updating pip packages..."
	brew_prefix="$(brew --prefix)"
	CFLAGS=-I$brew_prefix/include LDFLAGS=-L$brew_prefix/lib \
		pip install --user --upgrade pip setuptools pipenv
	pip list --user --format=columns --outdated |
		awk 'NR>2 {print $1}' |
		CFLAGS=-I$brew_prefix/include LDFLAGS=-L$brew_prefix/lib \
			xargs pip install --user --upgrade
fi
