#!/bin/bash
# Update Fonts
# Ensures that the Input family of fonts is installed and up to date.

. shell_utils

input_mono_url="https://input.fontbureau.com/build/?fontSelection=whole&a=ss&g=ss&i=serifs_round&l=serifs_round&zero=0&asterisk=0&braces=0&preset=default&line-height=1.2&accept=I+do"

tmp="$(mktemp -d)"

case "$(uname)" in
Darwin) destination="$HOME/Library/Fonts" ;;
Linux)
	destination="$HOME/.local/share/fonts/"
	;;
esac

wget "$input_mono_url" -O "$tmp/input.zip"
unzip -j -u -d "$destination" "$tmp/input.zip" "Input_Fonts/Input*"

# Clear font cache.
which fc-cache && fc-cache -fv
