#!/bin/bash
# Update python packages

installed pip && pip=pip
installed pip3 && pip=pip3

if [ "$pip" ]; then
  echo "Updating pip..."
  "$pip" install --user --upgrade pip setuptools pipenv
  "$pip" list --user --format=columns --outdated | awk 'NR>2 {print $1}' | xargs "$pip" install --user --upgrade

else
  echo "pip not found, skipping"
fi
