#!/bin/bash
# Update Arch Linux

if [ -e '/etc/arch-release' ]; then
	echo "Updating Arch Linux..."
	sudo pacman -Sy --noconfirm archlinux-keyring
	sudo pacman -Sy --noconfirm pacman-contrib
	sudo pacman -Syyu --noconfirm
	sudo pacman -Qtdq >/dev/null &&
		sudo pacman --noconfirm -Rns $(pacman -Qtdq)
	sudo paccache -ruk1

	installed yaourt && yaourt -Syyu --noconfirm
else
	echo "Not running Arch Linux, skipping"
fi
