#!/usr/bin/env bash

. shell_utils

if [ "$(uname)" = "Darwin" ]; then
	sudo xcode-select --install 2>&1 || echo The Xcode Command Line Tools package is already installed
else
	echo "macos not found, skipping"
fi
