#!/bin/bash
# Update Homebrew

# Test if $1 contains $2
contains () {
  case "$2" in
    *"$1"*)
      return 0 ;;
    *)
      return 1 ;;
  esac
}

if installed brew; then
  echo "Updating homebrew..."
  cd "$(brew --repo)"
  git prune
  git gc
  cd - > /dev/null
  brew update
  brew upgrade
  if contains "$*" "--HEAD"; then
    brew ls --versions | awk '/HEAD/ {print $1}' | xargs brew reinstall --HEAD
  fi
  brew cleanup
  brew prune
  brew doctor
  brew cask upgrade
  brew cask cleanup
else
  echo "Hombrew is not installed, skipping"
fi
