#!/bin/bash
# Update Arch Linux

ensure() {
  echo $pkgs | grep -q $1 >/dev/null || pacman -Sy --noconfirm $1
}

if [ -e '/etc/arch-release' ]; then
  echo "Updating Arch Linux..."
  pkgs=$(pacman -Q | awk '{print $1}')
  ensure archlinux-keyring
  ensure pacman-contrib
  sudo pacman -Syyu --noconfirm
  sudo pacman -Qtdq >/dev/null &&
    sudo pacman --noconfirm -Rns $(pacman -Qtdq)
  sudo paccache -ruk1

  yaourt -Syyu --noconfirm
else
  echo "Not running Arch Linux, skipping"
fi
