#!/bin/bash
# Update Clojure stuff

. bash_utils

if installed clojure; then
	echo "Updating $HOME/.clojure/deps.edn..."

	if installed xattr; then
		# Ensure java is out of quarantine.
		for dir in /Library/Java/JavaVirtualMachines/*; do
			xattr -l "$dir" | grep -q com.apple.quarantine ||
				xattr -d com.apple.quarantine "$dir"
		done
	fi

	clojure -Sdeps '{:deps {olical/depot {:mvn/version "1.8.4"}}}' -m depot.outdated.main --update "$HOME/.clojure/deps.edn"

	echo "Updating Leiningen if appropriate..."
	if installed lein; then
		lein upgrade
		lein ancient upgrade-profiles
	fi

	echo "Downloading zprint..."
	gh-download-latest kkinnear/zprint zprintm $HOME/.bin/zprint
	chmod +x $HOME/.bin/zprint

else
	echo "Clojure not found, skipping"
fi
