#!/bin/bash
# Update ruby gems

. bash_utils

if installed gem; then
	echo "Updating ruby gems..."

	export LDFLAGS="-L/usr/local/opt/ruby/lib"
	export CPPFLAGS="-I/usr/local/opt/ruby/include"

	# Always use homebrew ruby if it's installed
	gem install rubygems-update
	update_rubygems
	gem update
	gem clean
else
	echo "gem not installed, skipping"
fi
