#!/usr/bin/env bash

emacs_dir="$HOME/.emacs.d"

if [ -e "#$emacs_dir/.git" ] && [ -n "$(git -C "$emacs_dir" status --porcelain)" ]; then
	echo "Pulling changes from the current remote..."
	git -C "$HOME" pull
else
	echo "Not pulling becase no clean repo was found at $HOME."
fi

if [ -f "$emacs_dir/bin/setup" ]; then
	echo "Building a new version of Emacs..."
	"$emacs_dir/bin/setup"
else
	echo "Emacs build script not found, skipping"
fi
