#!/bin/bash
# Update fish shell

. bash_utils

if installed fish; then
	echo "Updating fish shell..."
	curl https://git.io/fisher --create-dirs -sLo "$HOME/.config/fish/functions/fisher.fish"
	fish -lc 'fisher self-update; and fisher'
else
	echo "fish shell not found, skipping"
fi
