#!/usr/bin/env bash

emacs_update="$HOME/.emacs.d/bin/update"

if installed emacs && [ -f "$emacs_update" ]; then
	echo "Updating Emacs..."
	"$emacs_update"
else
	echo "Emacs config not found, skipping..."
fi
