#!/usr/bin/env bash
# Recursively search up a directory tree (toward root)
# Useful for finding project files like Makefile and package.json

directory="$PWD"
while [ -n "$directory" ]; do
	[ -e "$directory/$1" ] && echo "$directory/$1" && return 0
	directory=${directory%/*}
done
return 1
