#!/usr/bin/env sh
 
# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Make sure we’re using the latest Homebrew
brew update
 
# Upgrade any already-installed formulae
brew upgrade

# Install Cask
brew install caskroom/cask/brew-cask

# Enable support for reading from a Brewfile
brew tap Homebrew/brewdler

# Read from the Brewfile in the current directory
brew brewdle

# Remove outdated versions from the cellar
brew cleanup

# Make sure everything is cleanly installed
brew doctor