#!/usr/bin/env sh

LEIN_FAST_TRAMPOLINE=y

LEIN_JVM_OPTS="-Djava.net.preferIPv4Stack=true -client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx2g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xverify:none -XX:+AggressiveOpts"

