# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Packages
install ack
install curl
install bash
install bash-completion
install fish
install git
install git-extras
install grc
install grep
install less
install lynx
install make
install midnight-commander
install nmap
install node
install openssh --with-brewed-openssl
install p7zip
install perl
install python --with-brewed-openssl
install python3 --with-brewed-openssl
install ruby
install speedtest-cli
install ssh-copy-id
install sshfs
install tree
install vim --override-system-vi
install vimpager
install wget

# GNU utils
install coreutils
install binutils
install diffutils
install ed --default-names
install findutils --default-names
install gawk
install gnu-indent --default-names
install gnu-sed --default-names
install gnu-tar --default-names
install gnu-which --default-names
install gnutls --default-names
install grep --default-names
install gzip
install screen
install watch
install wdiff --with-gettext
install wget

# Install Homebrew Cask
install caskroom/cask/brew-cask
update

# Casks
cask install iterm2
cask install google-chrome
cask install evernote
cask install alfred
cask install sublime-text
cask install keka
cask install qlstephen 
cask install qlcolorcode
cask install vlc
cask install osxfuse
cask install dash
cask install bittorrent-sync
cask install viscosity
cask install steam


# Clojure
cask install java
install clojure

# Remove outdated versions from the cellar
cleanup

# Make sure everything is cleanly installed
doctor