#!/usr/bin/env bash
# Bootstrap the dotfiles repo on a new computer
# $1: OPTIONAL: Path to repo

repo_remote="${1:-https://gitlab.com/mnewt/dotfiles.git}"
repo_name="$(basename "$repo_remote")"
repo_dir="$HOME/.config/repos"
repo_temp="$HOME/.config/repos/temp"

if [ -e "$HOME.git" || -e "repo_dir/$repo_name"]; then
  echo 
cd "$HOME"
mkdir -p "$repo_dir"
[ -e "$HOME/.git" ] && rm -rf "$HOME/.git"
git clone --separate-git-dir "$repo_dir/$repo_name" "$repo_remote" --no-checkout "$repo_temp"
mv "$repo_temp/.git" "$HOME"
rm -rf "$repo_temp"
git fetch
git reset --hard HEAD
git config --local status.showUntrackedFiles no
