#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

required=(autoconf texinfo libxml2 imagemagick librsvg libvterm)

echo Installing Dependencies...
brew install "${required[@]}" || echo Packages are already required.
brew upgrade "${required[@]}" || echo Packages are already up to date.

pushd "~/code/emacs"
echo Building Emacs...
git pull
git reset HEAD --hard
./autogen.sh
# The ctags bit is to rename the ctags binary so it doesn't conflict with an
# existing, non-emacs ctags installation
./configure --without-dbus --with-ns --disable-ns-self-contained --without-pop --with-modules CFLAGS="-I /usr/local/opt/libxml2/include/libxml2" --program-transform-name='s/^ctags$/ctags.emacs/'
# Even though we move the binary ourselves, we still need to install to get the
# Emacs Lisp source in the right place.
make install
rm -rf "$HOME/Applications/Emacs.app"
mv nextstep/Emacs.app "$HOME/Applications/"
make clean

popd
pushd "~/code/emacs-libvterm"
Echo Building VTerm...
git pull
git reset HEAD --hard
mkdir -p build
cd build
cmake ..
make

popd
