#!/usr/bin/env sh

# Install isync to sync IMAP. The rest are dependencies for mu.
brew_packages=autoconf automake libgpg-error libtool pkg-config gettext glib gmime xapian guile isync
brew install $brew_packages
brew update $brew_packages
brew services start isync ~/.scripts/homebrew.mxcl.isync.plist
# Homebrew often doesn't track recent versions of mu so we will build it from
# source. We assume we are in the source directory.
git pull
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
./autoconf.sh
make
