#!/usr/bin/env sh

# brew_pkgs="aspell autoconf bison libiconv libxslt python zlib"
# brew install $brew_pkgs
# brew install xapian --build-from-source --with-python
# brew upgrade $brew_pkgs xapian

sudo port install -N recoll aspell-dict-en py27-libxslt py27-libxml2 poppler
tesseract tesseract-eng exiftool antiword catdoc chmlib py27-chm

# pip install epub

# pushd

# cd $HOME/code/recoll

# git pull
# git reset HEAD --hard

# cd src

# ./autogen.sh
# ./configure --disable-qtgui --disable-webkit --disable-x11mon
# make

# popd
