#!/usr/bin/env sh

# Install a binary compiled with rust nightly (including SIMD and all
# optimizations) by utilizing a custom tap.
brew tap burntsushi/ripgrep https://github.com/BurntSushi/ripgrep.git
brew install ripgrep-bin
