#!/usr/bin/env sh

# Interactively install Xcode
open macappstores://itunes.apple.com/us/app/xcode/id497799835

# Interactively install Xcode Command Line Tools
xcode-select --install

# Ensure Xcode Command Line Tools are installed
xcode-select -p

